#!/bin/bash -e
#
# S2I run script for the 'springboot-sti' image.
# The run script executes the server that runs your application.
#
# For more information see the documentation:
#	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#


if [ -z "$TIMEZONE" ]; then
	echo "···································································································"
	echo "---->  VARIABLE TIMEZONE NO SETEADA - INICIANDO CON VALORES POR DEFECTO"
	echo "---->  POSIBLES VALORES: America/Montevideo | America/El_Salvador"
	echo "···································································································"
else
	echo "···································································································"
	echo "---->  TIMEZONE SETEADO ENCONTRADO: " $TIMEZONE
	echo "···································································································"
	cat /usr/share/zoneinfo/$TIMEZONE > /etc/localtime && \
	echo $TIMEZONE > /etc/timezone
fi



if [ ! -z "$WAITFOR_HOST" ] && [ ! -z "$WAITFOR_PORT" ] ; then
	echo "···································································································"
	echo "---->  WAITFOR  ACTIVADO.."
    until nc -z -v -w5 $WAITFOR_HOST $WAITFOR_PORT &> /dev/null; do echo waiting for $WAITFOR_HOST; sleep 15; done;	
	echo "···································································································"
fi


if [ -f /opt/custom_config/deployment.toml ]; then
cat /opt/custom_config/deployment.toml > /opt/wso2/repository/conf/deployment.toml
fi

if [ -f /opt/custom_config/master-datasources.xml ]; then
cat /opt/custom_config/master-datasources.xml > /opt/wso2/repository/conf/datasources/master-datasources.xml
fi

if [ -f /opt/custom_config/user-mgt.xml ]; then
cat /opt/custom_config/user-mgt.xml > /opt/wso2/repository/conf/user-mgt.xml
fi

if [ -f /opt/custom_config/registry.xml ]; then
cat /opt/custom_config/registry.xml > /opt/wso2/repository/conf/registry.xml
fi

if [ -f /opt/custom_config/carbon.xml ]; then
cat /opt/custom_config/carbon.xml > /opt/wso2/repository/conf/carbon.xml
fi

if [ -f /opt/custom_config/web.xml ]; then
cat /opt/custom_config/web.xml > /opt/wso2/repository/conf/tomcat/carbon/WEB-INF/web.xml
fi

if [ -f /opt/custom_config/catalina-server.xml ]; then
cat /opt/custom_config/catalina-server.xml > /opt/wso2/repository/conf/tomcat/catalina-server.xml
fi


if [ -f /opt/custom_config/api-manager.xml ]; then
cat /opt/custom_config/api-manager.xml > /opt/wso2/repository/conf/api-manager.xml
fi


if [ -f /opt/custom_config/site-publisher.json ]; then
cat /opt/custom_config/site-publisher.json > /opt/wso2/repository/deployment/server/jaggeryapps/publisher/site/conf/site.json
fi

if [ -f /opt/custom_config/site-store.json ]; then
cat /opt/custom_config/site-store.json > /opt/wso2/repository/deployment/server/jaggeryapps/store/site/conf/site.json
fi

if [ -f /opt/custom_config/site-admin.json ]; then
cat /opt/custom_config/site-admin.json > /opt/wso2/repository/deployment/server/jaggeryapps/admin/site/conf/site.json
fi


if [ -z $CUSTOM_JAVA_OPTS ]; then
export CUSTOM_JAVA_OPTS=
fi
echo "INICIANDO WSO2.."
export JVM_MEM_OPTS="$CUSTOM_JAVA_OPTS -XX:MaxRAMFraction=1 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dfile.encoding=UTF8 -XX:+ExitOnOutOfMemoryError -Djava.net.preferIPv4Stack=true"
exec /opt/wso2/bin/wso2server.sh 
